trigger:
- master

variables:
  CLICOLOR_FORCE: 1 # used by Base tools

jobs:
- job: windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: CMake@1
    displayName: 'Config'
    inputs:
      cmakeArgs: '.. -DCOLOR=1'
  
  - task: CMake@1
    displayName: 'Build'
    inputs:
      cmakeArgs: '--build . --config Debug --target install'

  - task: CmdLine@2
    displayName: 'Run tests'
    continueOnError: true
    inputs:
      script: |
        set PATH=%PATH%;$(System.DefaultWorkingDirectory)/build/Debug
        testsuite/Debug/unittesting --junit junit.xml
        ctest -T Test -C Debug
      workingDirectory: $(System.DefaultWorkingDirectory)/build

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/junit.xml'
      testRunTitle: 'Unittest results'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'cTest'
      testResultsFiles: '**/Test.xml'
      testRunTitle: 'Test results for CTest'

  - task: PublishPipelineArtifact@1
    inputs:
      artifactName: 'base-windows'
      targetPath: 'artifacts'
      path: $(System.DefaultWorkingDirectory)/build/install

- job: windows_arm64
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: CMake@1
    displayName: 'Config'
    inputs:
      cmakeArgs: '.. -A ARM64 -DCOLOR=1'
  
  - task: CMake@1
    displayName: 'Build'
    inputs:
      cmakeArgs: '--build . --config Debug --target install'

# TAG: need arm64 simulator for this to work or arm64 host
#  - task: CmdLine@2
#    displayName: 'Run tests'
#    continueOnError: true
#    inputs:
#      script: |
#        set PATH=%PATH%;$(System.DefaultWorkingDirectory)/build/Debug
#        testsuite/Debug/unittesting --junit junit.xml
#        ctest -T Test -C Debug
#      workingDirectory: $(System.DefaultWorkingDirectory)/build

#  - task: PublishTestResults@2
#    inputs:
#      testResultsFormat: 'JUnit'
#      testResultsFiles: '**/junit.xml'
#      testRunTitle: 'Unittest results'

#  - task: PublishTestResults@2
#    inputs:
#      testResultsFormat: 'cTest'
#      testResultsFiles: '**/Test.xml'
#      testRunTitle: 'Test results for CTest'

  - task: PublishPipelineArtifact@1
    inputs:
      artifactName: 'base-windows-arm64'
      targetPath: 'artifacts'
      path: $(System.DefaultWorkingDirectory)/build/install

- job: ubuntu18_04
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - task: CMake@1
    displayName: 'Config'
    inputs:
      cmakeArgs: '.. -DCOLOR=1'
  
  - task: CMake@1
    displayName: 'Build'
    inputs:
      cmakeArgs: '--build . --config Debug --target install -- -j 4'

  - task: CmdLine@2
    displayName: 'Run tests'
    continueOnError: true
    inputs:
      script: |
        ./testsuite/unittesting --junit junit.xml
        ctest -T Test
      workingDirectory: $(System.DefaultWorkingDirectory)/build

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/junit.xml'
      testRunTitle: 'Unittest results'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'cTest'
      testResultsFiles: '**/Test.xml'
      testRunTitle: 'Test results for CTest'

  - task: PublishPipelineArtifact@1
    inputs:
      artifactName: 'base-ubuntu18'
      targetPath: 'artifacts'
      path: $(System.DefaultWorkingDirectory)/build/install

- job: ubuntu16_04
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: CMake@1
    displayName: 'Config'
    inputs:
      cmakeArgs: '.. -DCOLOR=1'
  
  - task: CMake@1
    displayName: 'Build'
    inputs:
      cmakeArgs: '--build . --config Debug --target install -- -j 4'

  - task: CmdLine@2
    displayName: 'Run tests'
    continueOnError: true
    inputs:
      script: |
        ./testsuite/unittesting --junit junit.xml
        ctest -T Test
      workingDirectory: $(System.DefaultWorkingDirectory)/build

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/junit.xml'
      testRunTitle: 'Unittest results'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'cTest'
      testResultsFiles: '**/Test.xml'
      testRunTitle: 'Test results for CTest'

  - task: PublishPipelineArtifact@1
    inputs:
      artifactName: 'base-ubuntu16'
      targetPath: 'artifacts'
      path: $(System.DefaultWorkingDirectory)/build/install

- job: macos
  pool:
    vmImage: 'macOS-latest'
  steps:
  - task: CMake@1
    displayName: 'Config'
    inputs:
      cmakeArgs: '.. -DCOLOR=1'

  - task: CMake@1
    displayName: 'Build'
    inputs:
      cmakeArgs: '--build . --config Debug --target install -- -j 4'

  - task: CmdLine@2
    displayName: 'Run tests'
    continueOnError: true
    inputs:
      script: |
        ./testsuite/unittesting --junit junit.xml
        ctest -T Test
      workingDirectory: $(System.DefaultWorkingDirectory)/build

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/junit.xml'
      testRunTitle: 'Unittest results'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'cTest'
      testResultsFiles: '**/Test.xml'
      testRunTitle: 'Test results for CTest'

  - task: PublishPipelineArtifact@1
    inputs:
      artifactName: 'base-macos'
      targetPath: 'artifacts'
      path: $(System.DefaultWorkingDirectory)/build/install
