trigger:
- master

strategy:
  matrix:
    windows:
      imageName: 'windows-latest'
    linux:
      imageName: 'ubuntu-16.04'

pool:
  vmImage: $(imageName)

steps:
- task: CMake@1
  displayName: 'Config'
  inputs:
    cmakeArgs: '..'

- task: CMake@1
  displayName: 'Build'
  inputs:
    cmakeArgs: '--build . --config Debug --target install'

- task: CMake@1
  displayName: 'Run tests'
  inputs:
    cmakeArgs: '--build . --config Debug --target test'

- task: PublishPipelineArtifact@1
  inputs:
    artifactName: 'base'
    targetPath: 'artifacts'
    path: $(System.DefaultWorkingDirectory)/build/install
