#trigger: none
trigger:
  batch: true
  branches:
    include:
    - master

#pr:
#- master

#schedules:
#- cron: "0 0 * * *"
#  displayName: Daily build
#  branches:
#    include:
#    - master

variables:
  CLICOLOR_FORCE: 1 # used by Base tools

resources:
  containers:
  - container: centos
    image: renefonseca/base-centos8:latest
  - container: raspberrypi4
    image: renefonseca/base-raspberrypi4-64-debian:latest

jobs:
- job: centos8
  pool:
    vmImage: 'ubuntu-18.04'
  container: centos
  steps:
  - script: $(Build.SourcesDirectory)/ci/config.sh
    displayName: 'Config'
    workingDirectory: $(Build.BinariesDirectory)

  - script: $(Build.SourcesDirectory)/ci/build.sh
    displayName: 'Build'
    workingDirectory: $(Build.BinariesDirectory)

  - script: $(Build.SourcesDirectory)/ci/test.sh
    displayName: 'Run tests'
    continueOnError: true
    workingDirectory: $(Build.BinariesDirectory)

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/junit.xml'
      testRunTitle: 'Unittest results'
      workingDirectory: $(Build.BinariesDirectory)

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'cTest'
      testResultsFiles: '**/Test.xml'
      testRunTitle: 'Test results for CTest'
      workingDirectory: $(Build.BinariesDirectory)

- job: debian_arm64
  pool:
    vmImage: 'ubuntu-18.04'
  container: raspberrypi4
  steps:
  - script: $(Build.SourcesDirectory)/ci/config.sh
    displayName: 'Config'
    workingDirectory: $(Build.BinariesDirectory)

  - script: $(Build.SourcesDirectory)/ci/build.sh
    displayName: 'Build'
    workingDirectory: $(Build.BinariesDirectory)

  - script: $(Build.SourcesDirectory)/ci/test.sh
    displayName: 'Run tests'
    continueOnError: true
    workingDirectory: $(Build.BinariesDirectory)

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/junit.xml'
      testRunTitle: 'Unittest results'
      workingDirectory: $(Build.BinariesDirectory)

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'cTest'
      testResultsFiles: '**/Test.xml'
      testRunTitle: 'Test results for CTest'
      workingDirectory: $(Build.BinariesDirectory)
