trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: CMake@1
  inputs:
    cmakeArgs: '..'

- task: CMake@1
  inputs:
    cmakeArgs: '--build . --config Debug --target install'

- task: PublishPipelineArtifact@1
  inputs:
    artifact: 'base'
    targetPath: 'artifacts'
    path: $(System.DefaultWorkingDirectory)/build/install
